#include "perifericos.h"
#include "LPC17xx.h"
#include "GPIO_LPC17xx.h"
#include "PIN_LPC17xx.h"

void perif_init(void) {
	PIN_Configure(PUERTO_JOY, LEFT, PIN_FUNC_0, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
  PIN_Configure(PUERTO_JOY, DOWN, PIN_FUNC_0, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
  PIN_Configure(PUERTO_JOY, UP, PIN_FUNC_0, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
  PIN_Configure(PUERTO_JOY, CENTER, PIN_FUNC_0, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
  PIN_Configure(PUERTO_JOY, RIGHT, PIN_FUNC_0, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
  
  LPC_GPIOINT->IO0IntEnR = 1 << LEFT | 1 << DOWN | 1 << UP | 1 << CENTER | 1 << RIGHT;
  NVIC_EnableIRQ(EINT3_IRQn);
  LPC_GPIOINT->IO0IntClr = 1 << LEFT | 1 << DOWN | 1 << UP | 1 << CENTER | 1 << RIGHT;
  
  GPIO_SetDir (PUERTO_LED_RGB, RED, GPIO_DIR_OUTPUT);
  GPIO_SetDir (PUERTO_LED_RGB, GREEN, GPIO_DIR_OUTPUT);
  GPIO_SetDir (PUERTO_LED_RGB, BLUE, GPIO_DIR_OUTPUT);
  
  GPIO_PinWrite (PUERTO_LED_RGB, RED, 1);
  GPIO_PinWrite (PUERTO_LED_RGB, GREEN, 1);
  GPIO_PinWrite (PUERTO_LED_RGB, BLUE, 1);
}
